// constants/ofertas.js
export const featuredProducts = [
  { id: 2853, name: 'CHEDDAR FORTUNATA CREMOSO RECHEIO 1,010 KILO', category: 'Ofertas', price: 13.93, image: 'https://www.marquesvendaspmg.shop/images/cheddar-fortunata-cremoso-recheio-1010-kg-cx-8-bis.png' },
  { id: 2882, name: 'REQUEIJÃO FORTUNATA CREMOSO RECHEIO 1,010 KILO', category: 'Ofertas', price: 13.62, image: 'https://www.marquesvendaspmg.shop/images/requeijao-fortunata-cremoso-recheio-1010-kg-cx-8-bis.webp' },
  { id: 1098, name: 'ANÉIS DE CEBOLA CONGELADOS PRÉ FRITOS EMPANADOS PRÉ FORMADOS PICKERS MCCAIN 1,05 KILO (CX 10 PCT)', category: 'Ofertas', price: 218.43, image: 'https://www.marquesvendaspmg.shop/images/aneis-de-cebola-congelados-pre-fritos-empanados-pre-formados-mccain-105-kilo-cx-10-pct-pmg-atacadista.jpg' },
  { id: 1170, name: 'BATATA CONGELADA PRÉ FRITA COM CASCA RÚSTICA SKIN ON WEDGES MCCAIN 2,5 KILO (CX 5 PCT)', category: 'Ofertas', price: 204.01, image: 'https://www.marquesvendaspmg.shop/images/batata-congelada-pre-frita-com-casca-rustica-skin-on-wedges-mccain-25-kilo-cx-5-pct-pmg-atacadista.jpg' },
  { id: 1171, name: 'BATATA CONGELADA PRÉ FRITA COM CASCA RÚSTICA SURECRISP CRISPERS MCCAIN 2,5 KILO (CX 5 PCT)', category: 'Ofertas', price: 257.96, image: 'https://www.marquesvendaspmg.shop/images/batata-congelada-pre-frita-com-casca-rustica-surecrisp-crispers-mccain-25-kilo-cx-5-pct-pmg-atacadista.jpg' },
  { id: 1174, name: 'BATATA CONGELADA PRÉ FRITA FRY N DIP CANOA MCCAIN 2,5 KILO (CX 6 PCT)', category: 'Ofertas', price: 295.13, image: 'https://www.marquesvendaspmg.shop/images/batata-congelada-pre-frita-fry-n-dip-canoa-mccain-25-kilo-cx-6-pct-pmg-atacadista.jpg' },
  { id: 1176, name: 'BATATA CONGELADA PRÉ FRITA MAXI CHIPS MCCAIN 2 KILO (CX 5 PCT)', category: 'Ofertas', price: 314.80, image: 'https://www.marquesvendaspmg.shop/images/batata-congelada-pre-frita-maxi-chips-mccain-2-kilo-cx-5-pct-pmg-atacadista.jpg' },
  { id: 1177, name: 'BATATA CONGELADA PRÉ FRITA NOISETTES MCCAIN 2,5 KILO (CX 4 PCT)', category: 'Ofertas', price: 224.65, image: 'https://www.marquesvendaspmg.shop/images/batata-congelada-pre-frita-noisettes-mccain-25-kilo-cx-4-pct-pmg-atacadista.jpg' },
  { id: 1178, name: 'BATATA CONGELADA PRÉ FRITA SMILES SORRISO MCCAIN 1,5 KILO (CX 6 PCT)', category: 'Ofertas', price: 202.20, image: 'https://www.marquesvendaspmg.shop/images/batata-congelada-pre-frita-smiles-sorriso-mccain-15-kilo-cx-6-pct-pmg-atacadista.jpg' },
  { id: 1195, name: 'BATATA PALITO CONGELADA PRÉ FRITA 7 MM CORTE FINO MCCAIN 2,25 KILO (CX 8 PCT)', category: 'Ofertas', price: 259.32, image: 'https://www.marquesvendaspmg.shop/images/batata-palito-congelada-pre-frita-7-mm-corte-fino-mccain-225-kilo-cx-8-pct-pmg-atacadista.jpg' },
  { id: 1198, name: 'BATATA PALITO CONGELADA PRÉ FRITA 7 MM CORTE FINO SURECRISP EXTRA CROCANTE MCCAIN 2,5KILO (CX 5 PCT)', category: 'Ofertas', price: 219.94, image: 'https://www.marquesvendaspmg.shop/images/batata-palito-congelada-pre-frita-7-mm-corte-fino-surecrisp-extra-crocante-mccain-225-kilo-cx-8-pct-pmg-atacadista.jpg' },
  { id: 1203, name: 'BATATA PALITO CONGELADA PRÉ FRITA 9 MM CORTE TRADICIONAL MCCAIN 2,5 KILO (CX 6 PCT)', category: 'Ofertas', price: 203.72, image: 'https://www.marquesvendaspmg.shop/images/batata-palito-congelada-pre-frita-9-mm-corte-tradicional-mccain-25-kilo-cx-6-pct-pmg-atacadista.jpg' },
  { id: 1204, name: 'BATATA PALITO CONGELADA PRÉ FRITA 9 MM CORTE TRADICIONAL ONE FRY MCCAIN 2,5 KILO (CX 6 PCT)', category: 'Ofertas', price: 173.33, image: 'https://www.marquesvendaspmg.shop/images/batata-palito-congelada-pre-frita-9-mm-corte-tradicional-one-fry-mccain-25-kilo-cx-6-pct-pmg-atacadista.jpg' },
  { id: 1208, name: 'BATATA PALITO CONGELADA PRÉ FRITA 9 MM CORTE TRADICIONAL SURECRISP EXTRA CROCANTE MCCAIN 2,5 KILO (CX 6 PCT)', category: 'Ofertas', price: 244.50, image: 'https://www.marquesvendaspmg.shop/images/batata-palito-congelada-pre-frita-9-mm-corte-tradicional-surecrisp-extra-crocante-mccain-25-kilo-cx--pmg-atacadista.jpg' },
  { id: 1213, name: 'BATATA PALITO CONGELADA PRÉ FRITA CRINKLE FRIES ONDULADA MCCAIN 2,5 KILO (CX 5 PCT)', category: 'Ofertas', price: 206.59, image: 'https://www.marquesvendaspmg.shop/images/batata-palito-congelada-pre-frita-crinkle-fries-ondulada-mccain-25-kilo-cx-5-pct-pmg-atacadista.jpg' },
  { id: 1215, name: 'BATATA PALITO CONGELADA PRÉ FRITA CRINKLE SURECRISP TEMPERADA MCCAIN 2,5 KILO (CX 4 PCT)', category: 'Ofertas', price: 208.82, image: 'https://www.marquesvendaspmg.shop/images/batata-palito-congelada-pre-frita-crinkle-surecrisp-temperada-mccain-25-kilo-cx-4-pct-pmg-atacadista.jpg' },
  { id: 1895, name: 'CHEESE PILLOWS CONGELADO EMPANADO PICKERS MCCAIN 1 KILO (CX 6 PCT)', category: 'Ofertas', price: 443.19, image: 'https://www.marquesvendaspmg.shop/images/cheese-pillows-congelado-empanado-mccain-1-kilo-cx-6-pct-pmg-atacadista.jpg' },
  { id: 2162, name: 'BATATA PALITO CONGELADA PRÉ FRITA 7 MM CORTE FINO FAST FOOD MCCAIN 2,25 KILO (CX 8 PCT)', category: 'Ofertas', price: 222.94, image: 'https://www.marquesvendaspmg.shop/images/batata-palito-congelada-pre-frita-corte-fino-fast-food-mccain.png' },
  { id: 2164, name: 'BATATA PALITO CONGELADA PRÉ FRITA 7 MM SURECRISP SKIN ON MCCAIN 2,5 KILO (CX 5 PCT)', category: 'Ofertas', price: 228.43, image: 'https://www.marquesvendaspmg.shop/images/batata-palito-congelada-pre-frita-surecrisp-skin-on-mccain.png' },
  { id: 2426, name: 'BATATA PALITO CONGELADA PRÉ FRITA 7 MM CORTE FINO SURECRISP EXTRA CROCANTE MCCAIN 2,25 KILO (CX 8 PCT)', category: 'Ofertas', price: 316.11, image: 'https://www.marquesvendaspmg.shop/images/batata-palito-congelada-pre-frita-7-mm-corte-fino-surecrisp-extra-crocante-mccain-225-kg-cx-8-pct.webp' },
  { id: 1222, name: 'CAFÉ EXTRA FORTE ALMOFADA SELETO 500 G (FDO 10 PCT)', category: 'Ofertas', price: 197.44, image: 'https://www.marquesvendaspmg.shop/images/cafe-extra-forte-almofada-seleto-500-g-fdo-10-pct-pmg-atacadista.jpg' },
  { id: 1229, name: 'CAFÉ TRADICIONAL ALMOFADA SELETO 500 G (FDO 10 PCT)', category: 'Ofertas', price: 197.44, image: 'https://www.marquesvendaspmg.shop/images/cafe-tradicional-almofada-seleto-500-g-fdo-10-pct-pmg-atacadista.jpg' },
  { id: 1224, name: 'CAFÉ EXTRA FORTE ALMOFADA UNIÃO 500 G (CX 10 PCT)', category: 'Ofertas', price: 233.03, image: 'https://www.marquesvendaspmg.shop/images/cafe-extra-forte-almofada-uniao-500-g-cx-10-pct-pmg-atacadista.jpg' },
  { id: 1230, name: 'CAFÉ TRADICIONAL ALMOFADA UNIÃO 500 G (CX 10 PCT)', category: 'Ofertas', price: 233.03, image: 'https://www.marquesvendaspmg.shop/images/cafe-tradicional-almofada-uniao-500-g-cx-10-pct-pmg-atacadista.jpg' },
  { id: 1121, name: 'AZEITE DE OLIVA EXTRA VIRGEM COCINERO 500 ML', category: 'Ofertas', price: 23.15, image: 'https://www.marquesvendaspmg.shop/images/azeite-de-oliva-extra-virgem-cocinero-500-ml-pmg-atacadista.jpg' },
  { id: 1446, name: 'ATUM PEQUENO RALADO EM ÓLEO PESCADOR 140 G (CX 24 LT)', category: 'Ofertas', price: 170.53, image: 'https://www.marquesvendaspmg.shop/images/atum-pequeno-ralado-em-oleo-pescador-140-g-cx-24-lt-pmg-atacadista.jpg' },
  { id: 1450, name: 'ATUM PEQUENO SÓLIDO EM ÓLEO PESCADOR 140 G (CX 24 LT)', category: 'Ofertas', price: 221.47, image: 'https://www.marquesvendaspmg.shop/images/atum-pequeno-solido-em-oleo-pescador-140-g-cx-24-lt-pmg-atacadista.jpg' },
  { id: 2234, name: 'SARDINHAS EM ÓLEO PESCADOR 125 G (CX 54 LT)', category: 'Ofertas', price: 289.95, image: 'https://www.marquesvendaspmg.shop/images/sardinhas-em-oleo-pescador.png' },
  { id: 1439, name: 'ATUM PEDAÇOS EM ÓLEO POUCH COQUEIRO 480 G', category: 'Ofertas', price: 29.31, image: 'https://www.marquesvendaspmg.shop/images/atum-pedacos-em-oleo-pouch-coqueiro-480-g-pmg-atacadista.jpg' },
  { id: 1444, name: 'ATUM PEQUENO RALADO EM ÓLEO COQUEIRO 170 G (CX 24 LT)', category: 'Ofertas', price: 200.32, image: 'https://www.marquesvendaspmg.shop/images/atum-pequeno-ralado-em-oleo-coqueiro-170-g-cx-24-lt-pmg-atacadista.jpg' },
  { id: 1448, name: 'ATUM PEQUENO SÓLIDO EM ÓLEO COQUEIRO 170 G (CX 24 LT)', category: 'Ofertas', price: 265.03, image: 'https://www.marquesvendaspmg.shop/images/atum-pequeno-solido-em-oleo-coqueiro-170-g-cx-24-lt-pmg-atacadista.jpg' },
  { id: 1468, name: 'SARDINHAS EM ÓLEO COQUEIRO 125 G (CX 54 LT)', category: 'Ofertas', price: 321.84, image: 'https://www.marquesvendaspmg.shop/images/sardinhas-em-oleo-coqueiro-125-g-cx-54-lt-pmg-atacadista.jpg' },
  { id: 2587, name: 'MACARRÃO CARACOLINO COM OVOS SANTA AMÁLIA 500 G (FDO 20 PCT)', category: 'Ofertas', price: 72.04, image: 'https://www.marquesvendaspmg.shop/images/macarrao-caracolino-com-ovos-santa-amalia-500-g-fdo-20-pct.webp' },
  { id: 2591, name: 'MACARRÃO NINHO TALHARINE COM OVOS SANTA AMÁLIA 500 G (FDO 20 PCT)', category: 'Ofertas', price: 97.81, image: 'https://www.marquesvendaspmg.shop/images/macarrao-ninho-talharine-com-ovos-santa-amalia-500-g-fdo-20-pct.webp' },
];

// Array com os IDs em oferta (fácil de verificar)
export const IDs_EM_OFERTA = featuredProducts.map(p => p.id);

// Objeto para buscar preço de oferta por ID rapidamente
export const PRECO_OFERTA_POR_ID = Object.fromEntries(
  featuredProducts.map(p => [p.id, p.price])
);
